### ISSUE TITLE
ROS Kinetic で実行エラー

### ISSUE THREAD

**Issue by dif-engine** [YOODS/rovi#72]
Install.sh によってインストールしたのち launch すると次のようなエラーになる．

$ roslaunch rovi ycam3vga.launch
... logging to /home/openrtm/.ros/log/7d365360-ae02-11eb-a455-5cf9dd5bb198/roslaunch-dell-note5-5468.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:34969/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.17

NODES
  /
    ycam3vga (rovi/ycam3loader.sh)

auto-starting new master
process[master]: started with pid [5478]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 7d365360-ae02-11eb-a455-5cf9dd5bb198
process[rosout-1]: started with pid [5491]
started core service [/rosout]
process[ycam3vga-2]: started with pid [5500]
ERROR: Parameter [/rovi/camera/address] is not set
[ycam3loader] YOODS Co,LTD.-YCAM3D-III-
<type 'list'>
... logging to /home/openrtm/.ros/log/7d365360-ae02-11eb-a455-5cf9dd5bb198/roslaunch-dell-note5-5724.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:34350/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.17
 * /rovi/genpc/dump: /tmp

NODES
  /rovi/left/
    remap_node (rovi/remap_node)
  /rovi/
    genpc_node (rovi/genpc_node)
    ycam_ctrl (rovi/ycamctl.js)
  /rovi/right/
    remap_node (rovi/remap_node)

ROS_MASTER_URI=http://localhost:11311

process[rovi/left/remap_node-1]: started with pid [5744]
process[rovi/right/remap_node-2]: started with pid [5745]
process[rovi/genpc_node-3]: started with pid [5746]
process[rovi/ycam_ctrl-4]: started with pid [5769]
[ INFO] [1620261134.650248851]: genpc:reload ok
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'rosnodejs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/openrtm/catkin_ws/src/rovi/script/ycamctl.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[rovi/ycam_ctrl-4] process has died [pid 5769, exit code 1, cmd /home/openrtm/catkin_ws/src/rovi/script/ycamctl.js ycam3s __name:=ycam_ctrl __log:=/home/openrtm/.ros/log/7d365360-ae02-11eb-a455-5cf9dd5bb198/rovi-ycam_ctrl-4.log].
log file: /home/openrtm/.ros/log/7d365360-ae02-11eb-a455-5cf9dd5bb198/rovi-ycam_ctrl-4*.log

**Comment by dif-engine** [comment]
GettingStarted.md の rosnodejs 追加処理と pip install open3d-python --user をしたらエラーが変化して
osrun:stderr:[ERROR] [1620276720.449747779]: ros parameter url not set in camnode where’s the camera_info file?
になる．Install.sh にバグがあると思われる．
